#!/usr/bin/env python3
"""languages/cangjie/highlights.scm from tree-sitter-cangjie's queries/highlights.scm.

The grammar's queries are nvim-treesitter's, and Zed reads queries only from the extension, in the
capture names its themes know. Every capture the grammar uses is renamed, dropped or kept below; one
missing from the table fails, so a new capture upstream is a decision here, not a silent gap. Then
script/highlights.zed.scm, Zed's own refinements, is appended: the last pattern that matches wins.

    script/highlights.py <tree-sitter-cangjie checkout>           # write it
    script/highlights.py <tree-sitter-cangjie checkout> --check   # fail if it differs
"""
import re
import sys
from pathlib import Path

# nvim-treesitter's name -> Zed's
RENAMED = {
    "parameter": "variable.parameter",
    "variable.builtin": "variable.special",
    "character": "string",
    "markup.raw": "string.special",
}
# no color: nvim's spell checking
DROPPED = {"spell"}
# Zed's themes know them, or fall back along the dots (`function.macro` to `function`); `module`
# has no color in Zed, as in its Rust
KEPT = {
    "comment",
    "constant",
    "constant.builtin",
    "function",
    "function.macro",
    "keyword",
    "module",
    "number",
    "operator",
    "property",
    "punctuation.special",
    "string",
    "string.escape",
    "type",
    "type.builtin",
    "variable",
}

HEADER = """\
; Generated by script/highlights.py from tree-sitter-cangjie's queries/highlights.scm (MIT, BonZer0)
; at the revision extension.toml pins, in Zed's capture names; Zed's own patterns at the end come
; from script/highlights.zed.scm. Don't edit: move the pin and run the script.
; Until cjls's semantic tokens take over (cjls's D19).

"""

CAPTURE = re.compile(r"@([A-Za-z_][A-Za-z0-9_.]*)")


def split_comment(line: str) -> tuple[str, str]:
    """The code and the comment of a line: a `;` outside a string starts the comment."""
    in_string = False
    i = 0
    while i < len(line):
        c = line[i]
        if in_string and c == "\\":
            i += 2
            continue
        if c == '"':
            in_string = not in_string
        elif c == ";" and not in_string:
            return line[:i], line[i:]
        i += 1
    return line, ""


def convert(source: str) -> str:
    unknown = set()
    out = []
    for line in source.splitlines():
        code, comment = split_comment(line)
        names = CAPTURE.findall(code)
        if names and all(n in DROPPED for n in names) and code.count("(") == code.count(")"):
            continue  # a pattern that only captured what Zed drops
        def rename(m: re.Match) -> str:
            name = m.group(1)
            if name in RENAMED:
                return "@" + RENAMED[name]
            if name in DROPPED:
                return ""
            if name not in KEPT:
                unknown.add(name)
            return m.group(0)
        renamed = CAPTURE.sub(rename, code)
        if renamed != code:
            renamed = renamed.rstrip() + (" " + comment if comment else "")
            out.append(renamed)
        else:
            out.append(line)
    if unknown:
        sys.exit(
            "captures script/highlights.py does not map: "
            + ", ".join(sorted(unknown))
            + "\nadd each to RENAMED, DROPPED or KEPT"
        )
    body = re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip("\n")
    return body + "\n"


def main() -> None:
    args = [a for a in sys.argv[1:] if a != "--check"]
    if len(args) != 1:
        sys.exit(__doc__)
    here = Path(__file__).resolve().parent
    upstream = Path(args[0], "queries", "highlights.scm").read_text(encoding="utf-8")
    zed = (here / "highlights.zed.scm").read_text(encoding="utf-8")
    generated = HEADER + convert(upstream) + "\n" + zed
    target = here.parent / "languages" / "cangjie" / "highlights.scm"
    if "--check" in sys.argv:
        if target.read_text(encoding="utf-8") != generated:
            sys.exit(f"{target.relative_to(here.parent)} is not what script/highlights.py makes: run it")
    else:
        target.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
